# Generated by Django 4.0.3 on 2022-03-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archief', '0002_alter_genre_omschrijving_alter_persoon_geboortedatum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afbeelding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AV', 'Aankondiging voorkant'), ('AA', 'Aankondiging achterkant'), ('FL', 'Flyer'), ('P', 'Poster'), ('F', 'Foto')], default='F', max_length=2)),
                ('breedte', models.IntegerField(blank=True, null=True)),
                ('hoogte', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(height_field='hoogte', upload_to='', width_field='breedte')),
                ('stuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archief.stuk')),
            ],
        ),
    ]
