# Generated by Django 4.0.3 on 2022-03-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archief', '0003_afbeelding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afbeelding',
            options={'verbose_name_plural': 'afbeeldingen'},
        ),
        migrations.AlterModelOptions(
            name='deelname',
            options={'verbose_name_plural': 'deelnames'},
        ),
        migrations.AlterModelOptions(
            name='functie',
            options={'verbose_name_plural': 'functies'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='persoon',
            options={'verbose_name_plural': 'personen'},
        ),
        migrations.AlterModelOptions(
            name='stuk',
            options={'verbose_name_plural': 'stukken'},
        ),
        migrations.AlterModelOptions(
            name='uitvoering',
            options={'verbose_name_plural': 'uitvoeringen'},
        ),
        migrations.AlterField(
            model_name='persoon',
            name='lidnummer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
